image: node:14.16.1

cache:
  paths:
    - node_modules/

before_script:
  - yarn install

stages:
  - build
  - release

build:
  stage: build
  only:
    - master
  script:
    - yarn build
    - mv dist/* ./
  artifacts:
    paths:
      - module.json
      - lang/
      - module/
      - templates/

release:
  stage: release
  only:
    - master
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  release:
    tag_name: v${MAJOR}_${MINOR}_${REVISION}-alpha

