image: node:14.16.1

cache:
  paths:
    - node_modules/

before_script:
  - yarn install

stages:
  - build_deploy

build_&_deploy_app:
  stage: build_deploy
  only:
    - master
  script:
    - yarn build
    - mv dist pf1-kineticist-enhancements
  artifacts:
    paths:
      - pf1-kineticist-enhancements/*
