image: node:14.16.1

cache:
  paths:
    - node_modules/

before_script:
  - yarn install

stages:
  - build
  - release

build:
  stage: build
  only:
    - master
  script:
    - yarn build
    - mv dist/* ./
  artifacts:
    paths:
      - module.json
      - lang/
      - module/
      - templates/

release:
  image: node:13
  stage: release
  only:
    refs:
      - master
      - alpha
      # This matches maintenance branches
      - /^(([0-9]+)\.)?([0-9]+)\.x/
      # This matches pre-releases
      - /^([0-9]+)\.([0-9]+)\.([0-9]+)(?:-([0-9A-Za-z-]+(?:\.[0-9A-Za-z-]+)*))?(?:\+[0-9A-Za-z-]+)?$/
  script:
    - npm install @semantic-release/gitlab
    - npx semantic-release


#release:
#  stage: release
 # only:
 #   - master
  #image: registry.gitlab.com/gitlab-org/release-cli:latest
  #release:
  #  tag_name: v${MAJOR}_${MINOR}_${REVISION}-alpha

